name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: swift-lib-ssh-release
    steps:
      - id: app
        uses: actions/create-github-app-token@v2.2.1
        with:
          app-id: 1855004
          private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ steps.app.outputs.token }}
